version: '3.2'

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ticketing-app-server
    container_name: ticketing-app-node-server
    ports:
      - "5000:5000"
    env_file: ./server/.env

    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: ticketing-app-client
    container_name: ticketing-app-react-client
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge